/*
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Extended public API for LD2410 Radar Sensor
 *
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_SENSOR_LD2410_H_
#define ZEPHYR_INCLUDE_DRIVERS_SENSOR_LD2410_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <zephyr/drivers/sensor.h>

#define LD2410_GATE_COUNT 9

enum ld2410_target_state {
	NO_TAGET = 0,
	MOVING_TARGET,
	STATIONARY_TARGET,
	MOVING_AND_STATIONARY_TARGET
};

enum ld2410_gate_resolution {
	LD2410_GATE_RESOLUTION_75 = 0x00,
	LD2410_GATE_RESOLUTION_20 = 0x01
};

enum sensor_channel_ld2410 {
	SENSOR_CHAN_LD2410_MOVING_TARGET_DISTANCE = SENSOR_CHAN_PRIV_START,
	SENSOR_CHAN_LD2410_MOVING_TARGET_ENERGY,
	SENSOR_CHAN_LD2410_STATIONARY_TARGET_DISTANCE,
	SENSOR_CHAN_LD2410_STATIONARY_TARGET_ENERGY,
	SENSOR_CHAN_LD2410_TARGET_TYPE,
	SENSOR_CHAN_LD2410_MOVING_ENERGY_PER_GATE,
	SENSOR_CHAN_LD2410_STATIONARY_ENERGY_PER_GATE,
};

enum sensor_attribute_ld2410 {
	SENSOR_ATTR_LD2410_ENGINEERING_MODE = SENSOR_ATTR_PRIV_START,
	SENSOR_ATTR_LD2410_DISTANCE_RESOLUTION,
	SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_PER_GATE,
	SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_PER_GATE,
};

enum sensor_trigger_type_ld2410 {
	/** Trigger fires when a human presence is detected. */
	SENSOR_TRIG_HUMAN_PRESENCE = SENSOR_TRIG_PRIV_START,
};


#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_INCLUDE_DRIVERS_SENSOR_LD2410_H_ */
