/*
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Extended public API for LD2410 Radar Sensor
 *
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_SENSOR_LD2410_H_
#define ZEPHYR_INCLUDE_DRIVERS_SENSOR_LD2410_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <zephyr/drivers/sensor.h>

enum sensor_channel_ld2410 {
	SENSOR_CHAN_LD2410_MOVING_TARGET_DISTANCE = SENSOR_CHAN_PRIV_START,
    SENSOR_CHAN_LD2410_MOVING_TARGET_ENERGY,
    SENSOR_CHAN_LD2410_STATIONARY_TARGET_DISTANCE,
    SENSOR_CHAN_LD2410_STATIONARY_TARGET_ENERGY,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_0,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_1,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_2,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_3,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_4,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_5,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_6,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_7,
    SENSOR_CHAN_LD2410_MOVING_ENERGY_GATE_8,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_0,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_1,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_2,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_3,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_4,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_5,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_6,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_7,
    SENSOR_CHAN_LD2410_STATIONARY_ENERGY_GATE_8
};

enum sensor_attribute_ld2410 {
	SENSOR_ATTR_LD2410_ENGINEERING_MODE = SENSOR_ATTR_PRIV_START,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_0,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_1,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_2,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_3,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_4,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_5,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_6,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_7,
    SENSOR_ATTR_LD2410_MOVING_SENSITIVITY_GATE_8,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_0,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_1,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_2,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_3,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_4,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_5,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_6,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_7,
    SENSOR_ATTR_LD2410_STATIONARY_SENSITIVITY_GATE_8,
};

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_INCLUDE_DRIVERS_SENSOR_LD2410_H_ */
