# Copyright (c) 2025 Fabian Blatz <fabianblatz@gmail.com>
# SPDX-License-Identifier: Apache-2.0

CONFIG_DISK_ACCESS=y
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FILE_SYSTEM_MKFS=y

# Enable LittleFS with block device support
CONFIG_FS_LITTLEFS_BLK_DEV=y
CONFIG_FS_LITTLEFS_FMP_DEV=n

# Enable to create sample directory entries
CONFIG_FS_SAMPLE_CREATE_SOME_ENTRIES=y

# Enable drive formatting before mounting
CONFIG_FS_SAMPLE_FORMAT_DRIVE=y
